### ISSUE TITLE
Alternative implementation

### ISSUE THREAD

**Issue by PoomSmart** [level3tjg/YTMiniplayerEnabler#2]
Because the methods this tweak tries to hook are created dynamically, I propose an alternative solution that hooks just one method that is always available regardless of jailbreak.

And so you don't need fishhook because of its potential issue crashing on some devices: https://github.com/qnblackcat/uYouPlus/issues/163

![image](https://user-images.githubusercontent.com/3608783/168712330-9040afa7-68b3-49eb-803d-4873468fff62.png)

```
%hook YTWatchMiniBarViewController

- (void)updateMiniBarPlayerStateFromRenderer {}

%end
```

**Comment by level3tjg** [comment]
Saw this just after I pushed another change when realizing hooking class_addMethod was probably not the best way to go about it. Since class_addMethod will fail if the method already exists and calling the original isn't needed, creating them on init seems fine.

**Comment by PoomSmart** [comment]
That's a very good technique you have there.
